### ISSUE TITLE
zoom in and zoom out problem

### ISSUE THREAD

**Issue by toby941** [requtize/cropimg#12]
hi ,when i use demo, press the zoom in button,the Width and  Height of the crop image is become smaller and smaller,when i  press the zoom out button,the Width and  Height of the crop image is become bigger and bigger. my question is:how can i get the  rigth Width and the Height from the crop image?

**Comment by adambanaszkiewicz** [comment]
Hi there. When zooming, you have to imagine that you are not move image, but you are move the cropped area. When you want to crop smaller area, you decrease cropped area, and dimensions are become smaller. And other way, if you want to crop bigger area of image, you have to increase this area, and dimensions are become bigger.

The same thing happens here, but you are moving an image, instead a cropping area. When you zoom in, dimensions area become smaller, because the cropped area decrease. Preview not change it's size because this is main goal of this plugin - You are not move the cropped area, but a image.

This dimensions area are prepared for using in cropping methods/functions used in PHP, like [Imagick::cropImage](http://php.net/manual/en/imagick.cropimage.php) or others libraries writen by other PHPers. You get width and height of selected area on the image, and X, Y coordinates, where cropped area starts, on the original image (top-left corner).

I hope it helps. If not, ask what else you want to know :)
