### ISSUE TITLE
Zoom interval infinite loop

### ISSUE THREAD

**Issue by Noppey** [requtize/cropimg#7]
Hi,

It seems like when you click-and-hold the zoom-in button, and drag this button somewhat to the right, the interval that triggers the zoom doesn't get cleared. On mobile phones, this is also troubling, since you can't click-and-hold, so you will automatically will trigger this behavior when you try to zoom.

I solved this by changing the drawZoomingButtons to div's, instead of a-elements. This isn't a complete solution for mobile, since you can still not click-and-hold, but at least you won't end up with a non-clearable interval.

Perhaps you know a better solution that could fix mobile cropping completely.

Compliments on your project by the way, I tried a few croppers, but this was the first one that actually worked out of the box for me.

**Comment by adambanaszkiewicz** [comment]
Unfortunately, plugin was not tested on mobile devices and may not work on it. I will try fix this issue. Thank You for Your report.

Multiple plugin instances on one page was fixed in last release. Would You please write here, which version You use now?

**Comment by Noppey** [comment]
version 0.2.0, I only have one plugin on the page, it's also occurring in your demo.

Try to drag the zoom-in button to the right, do this twice. It will keep zooming and you're unable to stop it unless you refresh the page.

**Comment by cweissbrandmarker** [comment]
Hi there - how can i get the cropped and resized image ?! Thanks!

**Comment by adambanaszkiewicz** [comment]
I've test plugin behavior on situation you describe. There is a problem, but, i think there is really small percentage of people, who drag zoom-in button instead of clicking it. Buttons are designed for clicking, not for dragging. Zoom buttons have interval for zooming while user hold-up clicking (mousedown), and until mouseup event for body wasn't fires, zooming will be working. That's why, if you drag zoom button, zooming work all the time - because mouseup event wasn't trigger.

On mobile devices, you have right, maybe DIV instead of A element, will be better solution for buttons. I will think of this in bugfixes.

**Comment by adambanaszkiewicz** [comment]
I have made changes in generating HTML code of buttons. Now, instead A element, there are generated SPAN elements. This change should prevent described bug.
